import script for vale of white horse (closes #3192)
DemocracyClub/UK-Polling-Stations pull request #3339
Opened 2021-03-24 12:30 UTC by smsmith97

2021-03-25 12:27 UTC, smsmith97 commented
Okay, this should be in accordance with https://trello.com/c/1esahSyW/387-vale-of-white-horse now.

2021-03-25 16:33 UTC, smsmith97 commented
Changed again https://trello.com/c/1esahSyW/387-vale-of-white-horse

2021-03-26 13:57 UTC, GeoWill requested changes

2021-03-26 13:57 UTC, GeoWill commented on polling_stations/apps/data_importers/management/commands/import_vale_of_white_horse.py
> -        rec = super().address_record_to_dict(record)
I think this and the one above can stay in.

2021-03-30 12:44 UTC, GeoWill approved these changes

2021-03-30 12:45 UTC, merged