Import script for Torridge (2023-05-04) (closes #5489)
DemocracyClub/UK-Polling-Stations pull request #5569
Opened 2023-04-14 08:38 UTC by blacktyger

PR triggered by https://github.com/DemocracyClub/UK-Polling-Stations/issues/5489

2023-04-14 08:40 UTC, blacktyger commented
```python
# Newton St Petrock Community Centre, Newton St Petrock
if record.polling_place_id == "8386":
    record = record._replace(polling_place_postcode="EX22 7LW")

# West Croft School, Coronation Road, Bideford, EX39 3DD
if record.polling_place_id == "8149":
    record = record._replace(polling_place_postcode="EX39 3DE")
```
   
Trello ticket: https://trello.com/c/3TtyafRs/658-torridge

2023-04-17 09:43 UTC, GeoWill requested changes

2023-04-17 09:43 UTC, GeoWill commented on polling_stations/apps/data_importers/management/commands/import_torridge.py
> +    # csv_delimiter = "\t"
Can you delete this.

2023-04-20 08:10 UTC, GeoWill approved these changes

2023-04-20 08:10 UTC, merged