Import script for Spelthorne (2024-05-02) (closes #6235)
DemocracyClub/UK-Polling-Stations pull request #6236
Opened 2024-02-22 11:36 UTC by polling-bot-4000

PR triggered by upload at https://github.com/DemocracyClub/UK-Polling-Stations/issues/6235

2024-02-27 17:52 UTC, GeoWill requested changes
This looks like a bit of a confusing situation: 
With lines:
![image](https://github.com/DemocracyClub/UK-Polling-Stations/assets/20044500/58a15193-7e46-4b8b-9388-c83ac49be07a)
Without lines:
![image](https://github.com/DemocracyClub/UK-Polling-Stations/assets/20044500/d916412e-52db-4665-b78c-a539f565604f)
Could we double check with the council about it?

2024-02-28 09:24 UTC, blacktyger commented
https://app.asana.com/0/1205951895246773/1206707896421013

2024-03-07 11:11 UTC, blacktyger commented
Due to no council response dropping postcodes in question:

`"TW18 1HD", "TW18 1QP", "TW18 1QW", "TW18 1QL", "TW18 1QN", "TW18 1HH", "TW18 1HG", "TW18 1HQ", "TW18 1HJ"`

2024-03-07 15:55 UTC, GeoWill approved these changes

2024-03-07 15:55 UTC, merged